### ISSUE TITLE
Poznámky zo stretnutia so zadávateľom poslať zadávateľovi

### ISSUE THREAD

**Issue by pavelpetrovic** [TIS2023-FMFI/hviezdna-obloha#1]
Poslať zadávateľovi poznámky na kontrolu, prípadné doplnenie, môžeme uviesť aj ďalšie otázky.

**Comment by Marianna811** [comment]
Poznámky boli poslané zadávateľovi. Zadávateľ k nim nemal žiadne výhrady.


[Poznámky zo stretnutia (Projekt - Archivácia dát z pozorovaní).pdf](https://github.com/TIS2023-FMFI/hviezdna-obloha/files/12891922/Poznamky.zo.stretnutia.Projekt.-.Archivacia.dat.z.pozorovani.pdf)
