### ISSUE TITLE
Technológia pre webserver

### ISSUE THREAD

**Issue by Lonthre** [TIS2023-FMFI/hviezdna-obloha#4]

**Comment by adamova47** [comment]
Vybrala som Django, pretože je to robustný webový framework, ktorý poskytuje bezpečný základ pre webové aplikácie. Django môžete použiť na zostavenie backendu webovej aplikácie a použiť knižnice Pythonu na spracovanie súborov FITS.

**Comment by Lonthre** [comment]
Súhlasím, určite nám to dosť uľahčí prácu, lebo nemusíme s ním vymýšľať koleso a je to už taký industry standard
